//
//  Currencies.swift
//  LeBaluchon
//
//  Created by Greg on 14/09/2021.
//

import Foundation

let currencies = [
    "AED":"Dirham des Emirats Arabes Unis",
    "AFN":"Afghani Afghan",
    "ALL":"Lek albanais",
    "AMD":"Dram arménien",
    "ANG":"Florin des Antilles néerlandaises",
    "AOA":"Kwanza angolais",
    "ARS":"Peso argentin",
    "AUD":"Dollar australien",
    "AWG":"Aruba Florin",
    "AZN":"Azerbaijani Manat",
    "BAM":"Mark convertible de Bosnie-Herzégovine",
    "BBD":"Dollar barbadien",
    "BDT":"Bangladeshi Taka",
    "BGN":"Lev bulgare",
    "BHD":"Dinar bahreïni",
    "BIF":"Franc burundais",
    "BMD":"Dollar des Bermudes",
    "BND":"Dollar Brunéi",
    "BOB":"Boliviano bolivien",
    "BRL":"Réal brésilien",
    "BSD":"Dollar des Bahamas",
    "BTC":"Bitcoin",
    "BTN":"Ngultrum bhoutanais",
    "BWP":"Pula du Botswana",
    "BYN":"Nouveau rouble biélorusse",
    "BYR":"Rouble biélorusse",
    "BZD":"Belize Dollar",
    "CAD":"Dollar canadien",
    "CDF":"Franc Congolais",
    "CHF":"Franc Suisse",
    "CLF":"Unité de Compte Chilienne (UF)",
    "CLP":"Peso chilien",
    "CNY":"Yuan chinois",
    "COP":"Peso colombien",
    "CRC":"Colón costaricain",
    "CUC":"Peso Cubain Convertible",
    "CUP":"Peso Cubain",
    "CVE":"Escudo Cap-Verdien",
    "CZK":"République Tchèque Couronne",
    "DJF":"Franc Djiboutien",
    "DKK":"Couronne danoise",
    "DOP":"Peso dominicain",
    "DZD":"Dinar algérien",
    "EGP":"Livre égyptienne",
    "ERN":"Erythréen Nakfa",
    "ETB":"Birr éthiopien",
    "EUR":"Euro",
    "FJD":"Dollar fidjien",
    "FKP":"Falkland Islands Pound",
    "GBP":"Livre Sterling",
    "GEL":"Lari géorgien",
    "GGP":"Guernesey Pound",
    "GHS":"Cédi ghanéen",
    "GIP":"Livre de Gibraltar",
    "GMD":"Dalasi gambien",
    "GNF":"Franc guinéen",
    "GTQ":"Quetzal guatémaltèque",
    "GYD":"Dollar guyanais",
    "HKD":"Dollar de Hong Kong",
    "HNL":"Lempira hondurien",
    "HRK":"Kuna croate",
    "HTG":"Gourde haïtienne",
    "HUF":"Forint hongrois",
    "IDR":"Rupiah indonésienne",
    "ILS":"Israeli New Shekel",
    "IMP":"Livre mannoise",
    "INR":"Roupie indienne",
    "IQD":"Dinar irakien",
    "IRR":"Rial iranien",
    "ISK":"Couronne islandaise",
    "JEP":"Jersey Pound",
    "JMD":"Dollar jamaïcain",
    "JOD":"Dinar jordanien",
    "JPY":"Yen japonais",
    "KES":"Shilling kenyan",
    "KGS":"Kirghizistan Som",
    "KHR":"Riel cambodgien",
    "KMF":"Franc comorien",
    "KPW":"Won nord-coréen",
    "KRW":"Won sud-coréen",
    "KWD":"Dinar koweïtien",
    "KYD":"Dollar des îles Caïmans",
    "KZT":"Tenge kazakh",
    "LAK":"Kip laotien",
    "LBP":"Livre libanaise",
    "LKR":"Roupie sri lankaise",
    "LRD":"Dollar libérien",
    "LSL":"Lesotho Loti",
    "LTL":"Litas lituanien",
    "LVL":"Lats letton",
    "LYD":"Dinar libyen",
    "MAD":"Dirham marocain",
    "MDL":"Leu moldave",
    "MGA":"Ariary malgache",
    "MKD":"Denar macédonien",
    "MMK":"Myanma Kyat",
    "MNT":"Tugrik mongol",
    "MOP":"Pataca macanais",
    "MRO":"Ouguiya mauritanien",
    "MUR":"Roupie mauricienne",
    "MVR":"Rufiyaa maldivienne",
    "MWK":"Kwacha malawite",
    "MXN":"Peso mexicain",
    "MYR":"Ringgit malais",
    "MZN":"Metical mozambicain",
    "NAD":"Dollar namibien",
    "NGN":"Naira nigérian",
    "NIO":"Córdoba nicaraguayen",
    "NOK":"Couronne norvégienne",
    "NPR":"Roupie népalaise",
    "NZD":"Dollar néo-zélandais",
    "OMR":"Rial omanais",
    "PAB":"Balboa panaméen",
    "PEN":"Nuevo Sol péruvien",
    "PGK":"Kina de Papouasie-Nouvelle-Guinée",
    "PHP":"Peso philippin",
    "PKR":"Roupie pakistanaise",
    "PLN":"Zloty polonais",
    "PYG":"Paraguayen Guarani",
    "QAR":"Rial qatari",
    "RON":"Leu roumain",
    "RSD":"Dinar serbe",
    "RUB":"Rouble russe",
    "RWF":"Franc rwandais",
    "SAR":"Rial saoudien",
    "SBD":"Dollar des îles Salomon",
    "SCR":"Roupie seychelloise",
    "SDG":"Livre soudanaise",
    "SEK":"Couronne suédoise",
    "SGD":"Dollar de Singapour",
    "SHP":"Livre de Sainte-Hélène",
    "SLL":"Sierra Leonean Leone",
    "SOS":"Shilling somalien",
    "SRD":"Dollar Suriname",
    "STD":"São Tomé et Príncipe Dobra",
    "SVC":"Colón salvadorien",
    "SYP":"Livre syrienne",
    "SZL":"Swazi Lilangeni",
    "THB":"Baht thaïlandais",
    "TJS":"Tadjikistan Somoni",
    "TMT":"Turkmenistani Manat",
    "TND":"Dinar tunisien",
    "TOP":"Pa'anga tongan",
    "TRY":"Lira turque",
    "TTD":"Dollar de Trinité-et-Tobago",
    "TWD":"Nouveau dollar de Taïwan",
    "TZS":"Shilling tanzanien",
    "UAH":"Hryvnia ukrainienne",
    "UGX":"Shilling ougandais",
    "USD":"Dollar des États-Unis",
    "UYU":"Peso uruguayen",
    "UZS":"Ouzbékistan Som",
    "VEF":"Bolivar vénézuélien Fuerte ",
    "VND":"Dong vietnamien",
    "VUV":"Vanuatu Vatu",
    "WST":"Tala samoan",
    "XAF":"Franc CFA BEAC",
    "XAG":"Argent (once troy)",
    "XAU":"Or (once troy)",
    "XCD":"Dollar des Caraïbes orientales",
    "XDR":"Droits de tirage spéciaux",
    "XOF":"Franc CFA BCEAO",
    "XPF":"Franc CFP",
    "YER":"Rial yéménite",
    "ZAR":"Rand sud-africain",
    "ZMK":"Kwacha zambien (avant 2013)",
    "ZMW":"Kwacha zambien",
    "ZWL":"Dollar zimbabwéen"]
